### ISSUE TITLE
Folder Process

### ISSUE THREAD

**Issue by rohanrudra55** [Maaitrayo/video-to-image-converter#4]
# Lists

###### Folder name: _99c94dc769b5d96e_2018-11-16--10-00-42_
---
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\32\video.hevc
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\33\video.hevc
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\34\video.hevc
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\35\video.hevc
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\36\video.hevc
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\37\video.hevc
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\38\video.hevc
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\39\video.hevc
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\40\video.hevc
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\41\video.hevc
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\42\video.hevc
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\43\video.hevc
- [x] Chunk_10_5-003\99c94dc769b5d96e_2018-11-16--10-00-42\44\video.hevc
---
**Comment and mark when done**

**Comment by Maaitrayo** [comment]
>frames saved in (SANDS OF TIME DATA\Images)(000000 - 001166).png files(32)

**Comment by rohanrudra55** [comment]
# Lists 2 

###### Folder name: _99c94dc769b5d96e_2018-11-16--15-02-13_
---

_Pending..._
@rohanrudra55 
---
**Comment and mark when done**

**Comment by Maaitrayo** [comment]
frames saved in (SANDS OF TIME DATA\Images)(001167-002333).png files(33)

**Comment by Maaitrayo** [comment]
frames saved in (SANDS OF TIME DATA\Images)(002334-003500).png files(34)

**Comment by Maaitrayo** [comment]
frames saved in (SANDS OF TIME DATA\Images)(003501-004667).png files(35)

**Comment by Maaitrayo** [comment]
frames saved in (SANDS OF TIME DATA\Images)(004668-005834).png files(36)

**Comment by Maaitrayo** [comment]
frames saved in (SANDS OF TIME DATA\Images)(005835-007001).png files(37)

**Comment by Maaitrayo** [comment]
frames saved in (SANDS OF TIME DATA\Images)(007002-008168).png files(38)

**Comment by Maaitrayo** [comment]
frames saved in (SANDS OF TIME DATA\Images)(008169-009335).png files(39)

**Comment by Maaitrayo** [comment]
frames saved in (SANDS OF TIME DATA\Images)(009336-010502).png files(40)

**Comment by Maaitrayo** [comment]
frames saved in (SANDS OF TIME DATA\Images)(010503-011669).png files(41)

**Comment by Maaitrayo** [comment]
frames saved in (SANDS OF TIME DATA\Images)(011670-012837).png files(42)

**Comment by Maaitrayo** [comment]
frames saved in (SANDS OF TIME DATA\Images)(012838-014036).png files(43)

**Comment by Maaitrayo** [comment]
frames saved in (SANDS OF TIME DATA\Images)(014037-015204).png files(44)

**Comment by Maaitrayo** [comment]
First hashed file( 99c94dc769b5d96e_2018-11-16--10-00-42) videos converted to images and stored frame wise subtracting 33 frames from the last
